'use client';

import type { EnergyType } from '@/types/energy';
import { EnergyIcon } from './EnergyIcon';
import { EnergyTooltip } from './EnergyTooltip';

interface EnergyTypeSelectorProps {
  selectedTypes: EnergyType[];
  onToggleType: (type: EnergyType) => void;
}

const TYPES: { id: EnergyType; label: string; tooltip: string }[] = [
  { id: 'solar', label: 'Solar', tooltip: "Energy captured from the sun's radiation. Highly renewable and low emission." },
  { id: 'wind', label: 'Wind', tooltip: 'Power generated by harnessing wind currents. Zero direct emissions.' },
  { id: 'hydro', label: 'Hydro', tooltip: 'Energy from flowing water. Highly efficient and reliable baseload power.' },
  { id: 'geothermal', label: 'Geothermal', tooltip: 'Heat extracted from the earth. Provides stable, continuous renewable energy.' },
  { id: 'biomass', label: 'Biomass', tooltip: 'Energy produced from organic materials. Carbon neutral when managed sustainably.' }
];

export function EnergyTypeSelector({ selectedTypes, onToggleType }: EnergyTypeSelectorProps) {
  return (
    <div className="grid grid-cols-2 md:grid-cols-5 gap-3 w-full">
      {TYPES.map((t) => {
        const isSelected = selectedTypes.includes(t.id);
        return (
          <EnergyTooltip key={t.id} content={t.tooltip}>
            <button
              onClick={() => onToggleType(t.id)}
              className={`w-full flex flex-col items-center justify-center p-4 rounded-xl border-2 transition-all duration-200 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-blue-500 ${
                isSelected ? 'border-blue-600 bg-blue-50 shadow-sm' : 'border-gray-200 bg-white hover:border-blue-300 hover:bg-gray-50'
              }`}
            >
              <EnergyIcon type={t.id} className={`w-7 h-7 mb-2 ${isSelected ? 'opacity-100' : 'opacity-70'}`} />
              <span className={`text-sm font-semibold ${isSelected ? 'text-blue-800' : 'text-gray-600'}`}>{t.label}</span>
            </button>
          </EnergyTooltip>
        );
      })}
    </div>
  );
}