import {
  MobileWalletProvider,
  WalletAnalyticsSnapshot,
  WalletConnection,
  WalletSyncSnapshot,
} from '@/types/mobile-wallet'

const institutionalStandards = ['PCI DSS', 'PSD2', 'Biometric MFA', 'Device Integrity'] as const
const enhancedStandards = ['PCI DSS', 'SOC 2', 'Biometric MFA'] as const

const mobileWalletCatalog: MobileWalletProvider[] = [
  {
    id: 'apple-wallet',
    name: 'Apple Wallet',
    platform: 'ios',
    categories: ['native'],
    logoAccent: 'from-slate-900 to-slate-700',
    description: 'Native iPhone wallet with biometric confirmation and tap-to-pay flows.',
    supportedCountries: 68,
    averageOperationTimeMs: 420,
    supportsEnergyTrading: true,
    supportsBankLinking: true,
    supportsNativeDeepLink: true,
    mobileReadinessScore: 99,
    riskScore: 95,
    energyTradingFeatures: ['one-tap energy checkout', 'biometric approvals', 'tokenized utility cards'],
    bankingAppIds: ['monzo-us', 'revolut-business'],
    security: {
      biometricAuth: true,
      deviceBinding: true,
      fraudMonitoring: true,
      encryption: 'secure-enclave',
      securityTier: 'institutional',
      complianceBadges: ['PCI DSS', 'PSD2', 'Biometric MFA'],
      standards: [...institutionalStandards],
    },
  },
  {
    id: 'google-wallet',
    name: 'Google Wallet',
    platform: 'android',
    categories: ['native'],
    logoAccent: 'from-blue-600 to-green-500',
    description: 'Fast Android checkout and credential storage across supported devices.',
    supportedCountries: 65,
    averageOperationTimeMs: 460,
    supportsEnergyTrading: true,
    supportsBankLinking: true,
    supportsNativeDeepLink: true,
    mobileReadinessScore: 98,
    riskScore: 93,
    energyTradingFeatures: ['native energy passes', 'deep-link approvals', 'tokenized meter payments'],
    bankingAppIds: ['revolut-business', 'monzo-us'],
    security: {
      biometricAuth: true,
      deviceBinding: true,
      fraudMonitoring: true,
      encryption: 'hardware-backed',
      securityTier: 'institutional',
      complianceBadges: ['PCI DSS', 'Device Integrity', 'Tokenized Payments'],
      standards: [...institutionalStandards, 'Tokenized Payments'],
    },
  },
  {
    id: 'samsung-wallet',
    name: 'Samsung Wallet',
    platform: 'android',
    categories: ['native'],
    logoAccent: 'from-indigo-600 to-sky-500',
    description: 'Knox-backed wallet support for Samsung mobile payments and passes.',
    supportedCountries: 29,
    averageOperationTimeMs: 480,
    supportsEnergyTrading: true,
    supportsBankLinking: true,
    supportsNativeDeepLink: true,
    mobileReadinessScore: 97,
    riskScore: 91,
    energyTradingFeatures: ['Knox-secured approvals', 'utility credential storage', 'fast merchant-present pay'],
    bankingAppIds: ['revolut-business'],
    security: {
      biometricAuth: true,
      deviceBinding: true,
      fraudMonitoring: true,
      encryption: 'hardware-backed',
      securityTier: 'institutional',
      complianceBadges: ['Samsung Knox', 'Tokenized Cards', 'Biometric MFA'],
      standards: [...institutionalStandards, 'Tokenized Payments'],
    },
  },
  {
    id: 'paypal',
    name: 'PayPal',
    platform: 'cross-platform',
    categories: ['super-app'],
    logoAccent: 'from-blue-700 to-cyan-500',
    description: 'Mobile checkout and stored balance for global energy credits.',
    supportedCountries: 200,
    averageOperationTimeMs: 510,
    supportsEnergyTrading: true,
    supportsBankLinking: true,
    supportsNativeDeepLink: true,
    mobileReadinessScore: 95,
    riskScore: 90,
    energyTradingFeatures: ['stored balance settlement', 'merchant QR fallback', 'instant top ups'],
    bankingAppIds: ['monzo-us', 'community-solar-cu'],
    security: {
      biometricAuth: true,
      deviceBinding: true,
      fraudMonitoring: true,
      encryption: 'AES-256',
      securityTier: 'enhanced',
      complianceBadges: ['PCI DSS', 'Fraud Shield'],
      standards: [...enhancedStandards],
    },
  },
  {
    id: 'cash-app',
    name: 'Cash App',
    platform: 'cross-platform',
    categories: ['super-app'],
    logoAccent: 'from-emerald-500 to-lime-500',
    description: 'Instant peer and merchant transfers with a mobile-first UX.',
    supportedCountries: 2,
    averageOperationTimeMs: 530,
    supportsEnergyTrading: true,
    supportsBankLinking: true,
    supportsNativeDeepLink: true,
    mobileReadinessScore: 93,
    riskScore: 88,
    energyTradingFeatures: ['wallet balance checkout', 'repeat purchase shortcuts', 'utility pay requests'],
    bankingAppIds: ['community-solar-cu'],
    security: {
      biometricAuth: true,
      deviceBinding: true,
      fraudMonitoring: true,
      encryption: 'AES-256',
      securityTier: 'enhanced',
      complianceBadges: ['Biometric MFA', 'Fraud Shield'],
      standards: [...enhancedStandards],
    },
  },
  {
    id: 'venmo',
    name: 'Venmo',
    platform: 'cross-platform',
    categories: ['super-app'],
    logoAccent: 'from-sky-600 to-blue-500',
    description: 'Consumer wallet with one-tap payments and social transfer familiarity.',
    supportedCountries: 1,
    averageOperationTimeMs: 550,
    supportsEnergyTrading: true,
    supportsBankLinking: true,
    supportsNativeDeepLink: true,
    mobileReadinessScore: 91,
    riskScore: 87,
    energyTradingFeatures: ['consumer funding flows', 'stored contacts for cooperatives', 'instant balance checks'],
    bankingAppIds: ['community-solar-cu'],
    security: {
      biometricAuth: true,
      deviceBinding: true,
      fraudMonitoring: true,
      encryption: 'AES-256',
      securityTier: 'enhanced',
      complianceBadges: ['Biometric MFA', 'Velocity Checks'],
      standards: [...enhancedStandards],
    },
  },
  {
    id: 'revolut',
    name: 'Revolut',
    platform: 'cross-platform',
    categories: ['banking'],
    logoAccent: 'from-slate-800 to-slate-500',
    description: 'Mobile banking wallet with real-time balances and virtual cards.',
    supportedCountries: 38,
    averageOperationTimeMs: 520,
    supportsEnergyTrading: true,
    supportsBankLinking: true,
    supportsNativeDeepLink: true,
    mobileReadinessScore: 96,
    riskScore: 92,
    energyTradingFeatures: ['open banking auth', 'real-time balance sync', 'virtual card fallback'],
    bankingAppIds: ['revolut-business'],
    security: {
      biometricAuth: true,
      deviceBinding: true,
      fraudMonitoring: true,
      encryption: 'AES-256',
      securityTier: 'institutional',
      complianceBadges: ['PSD2', 'Biometric MFA', 'Card Controls'],
      standards: [...institutionalStandards],
    },
  },
  {
    id: 'mpesa',
    name: 'M-Pesa',
    platform: 'android',
    categories: ['super-app'],
    logoAccent: 'from-green-700 to-green-500',
    description: 'Mobile money wallet suited to utility and energy settlement flows.',
    supportedCountries: 7,
    averageOperationTimeMs: 610,
    supportsEnergyTrading: true,
    supportsBankLinking: true,
    supportsNativeDeepLink: true,
    mobileReadinessScore: 90,
    riskScore: 86,
    energyTradingFeatures: ['utility QR settlement', 'agent assisted cash in', 'offline resilience'],
    bankingAppIds: ['community-solar-cu'],
    security: {
      biometricAuth: false,
      deviceBinding: true,
      fraudMonitoring: true,
      encryption: 'AES-256',
      securityTier: 'enhanced',
      complianceBadges: ['SIM Binding', 'Fraud Monitoring'],
      standards: ['PCI DSS', 'SOC 2'],
    },
  },
  {
    id: 'monzo',
    name: 'Monzo',
    platform: 'cross-platform',
    categories: ['banking'],
    logoAccent: 'from-orange-500 to-pink-500',
    description: 'Banking app with instant transaction updates and budgeting controls.',
    supportedCountries: 1,
    averageOperationTimeMs: 470,
    supportsEnergyTrading: true,
    supportsBankLinking: true,
    supportsNativeDeepLink: true,
    mobileReadinessScore: 97,
    riskScore: 90,
    energyTradingFeatures: ['budget-aware energy spend', 'real-time balance checks', 'bank app redirect'],
    bankingAppIds: ['monzo-us'],
    security: {
      biometricAuth: true,
      deviceBinding: true,
      fraudMonitoring: true,
      encryption: 'AES-256',
      securityTier: 'institutional',
      complianceBadges: ['PSD2', 'Real-time Alerts'],
      standards: [...institutionalStandards],
    },
  },
  {
    id: 'coinbase-wallet',
    name: 'Coinbase Wallet',
    platform: 'cross-platform',
    categories: ['exchange', 'defi'],
    logoAccent: 'from-blue-600 to-indigo-600',
    description: 'Self-custody wallet for tokenized energy positions and stablecoin rails.',
    supportedCountries: 70,
    averageOperationTimeMs: 560,
    supportsEnergyTrading: true,
    supportsBankLinking: false,
    supportsNativeDeepLink: true,
    mobileReadinessScore: 92,
    riskScore: 89,
    energyTradingFeatures: ['stablecoin settlement', 'self-custody escrow', 'tokenized REC support'],
    bankingAppIds: [],
    security: {
      biometricAuth: true,
      deviceBinding: true,
      fraudMonitoring: true,
      encryption: 'AES-256',
      securityTier: 'enhanced',
      complianceBadges: ['Seed Vault', 'Biometric MFA'],
      standards: [...enhancedStandards],
    },
  },
  {
    id: 'metamask-mobile',
    name: 'MetaMask Mobile',
    platform: 'cross-platform',
    categories: ['defi'],
    logoAccent: 'from-orange-500 to-amber-500',
    description: 'DeFi wallet for tokenized settlement and programmable trading approvals.',
    supportedCountries: 120,
    averageOperationTimeMs: 590,
    supportsEnergyTrading: true,
    supportsBankLinking: false,
    supportsNativeDeepLink: true,
    mobileReadinessScore: 89,
    riskScore: 84,
    energyTradingFeatures: ['programmable approvals', 'gas aware signing', 'energy token swaps'],
    bankingAppIds: [],
    security: {
      biometricAuth: true,
      deviceBinding: true,
      fraudMonitoring: true,
      encryption: 'AES-256',
      securityTier: 'enhanced',
      complianceBadges: ['Transaction Simulation', 'Biometric MFA'],
      standards: [...enhancedStandards],
    },
  },
  {
    id: 'phantom',
    name: 'Phantom',
    platform: 'cross-platform',
    categories: ['defi', 'energy'],
    logoAccent: 'from-fuchsia-500 to-indigo-500',
    description: 'Mobile wallet optimized for fast asset approvals and low-friction signing.',
    supportedCountries: 90,
    averageOperationTimeMs: 500,
    supportsEnergyTrading: true,
    supportsBankLinking: false,
    supportsNativeDeepLink: true,
    mobileReadinessScore: 94,
    riskScore: 85,
    energyTradingFeatures: ['fast signing', 'energy pool positions', 'mobile-first repeat purchases'],
    bankingAppIds: [],
    security: {
      biometricAuth: true,
      deviceBinding: true,
      fraudMonitoring: true,
      encryption: 'AES-256',
      securityTier: 'enhanced',
      complianceBadges: ['Transaction Previews', 'Biometric MFA'],
      standards: [...enhancedStandards],
    },
  },
]

const analyticsSnapshot: WalletAnalyticsSnapshot = {
  activeMobileWallets: 12,
  mobileConversionRate: 0.78,
  repeatWalletUsageRate: 0.64,
  averagePaymentTimeMs: 2800,
  preferredPaymentRail: 'instant-bank',
  peakUsageWindow: '6:00 PM - 9:00 PM',
  topWallets: ['Apple Wallet', 'Google Wallet', 'Revolut', 'Phantom'],
  usagePatterns: [
    { label: 'Repeat buyers', share: 0.42 },
    { label: 'First-time mobile users', share: 0.24 },
    { label: 'Bank-funded settlements', share: 0.21 },
    { label: 'Wallet balance settlements', share: 0.13 },
  ],
  paymentFlow: {
    previousStepCount: 6,
    optimizedStepCount: 3,
    reducedStepsPercent: 50,
    medianCompletionMs: 2800,
    walletOperationBudgetMs: 1000,
  },
  securityAudit: {
    status: 'pass',
    standards: ['PCI DSS', 'PSD2', 'SOC 2', 'Biometric MFA', 'Device Integrity'],
    biometricCoveragePercent: 92,
    fraudDetectionLatencyMs: 310,
    lastAuditAt: '2026-03-20T16:00:00.000Z',
  },
}

function delay(ms: number) {
  return new Promise((resolve) => setTimeout(resolve, ms))
}

function createWalletAddress(walletId: string) {
  const normalized = walletId.replace(/[^a-z0-9]/gi, '').slice(0, 10).toUpperCase()
  return `CUR-${normalized}-A91X`
}

export const mobileWalletService = {
  async listWallets(): Promise<MobileWalletProvider[]> {
    await delay(120)
    return mobileWalletCatalog
  },

  async connectWallet(walletId: string): Promise<WalletConnection> {
    await delay(420)
    return {
      walletId,
      status: 'connected',
      connectedAt: new Date().toISOString(),
      walletAddress: createWalletAddress(walletId),
      approvalTimeMs: 420,
    }
  },

  async getWalletSyncSnapshot(): Promise<WalletSyncSnapshot> {
    await delay(240)
    return {
      devices: [
        {
          id: 'device-iphone',
          deviceName: 'iPhone 15 Pro',
          platform: 'ios',
          lastSyncedAt: '2026-03-24T09:32:00.000Z',
          syncState: 'healthy',
        },
        {
          id: 'device-pixel',
          deviceName: 'Pixel 9',
          platform: 'android',
          lastSyncedAt: '2026-03-24T09:31:44.000Z',
          syncState: 'healthy',
        },
        {
          id: 'device-web',
          deviceName: 'Tablet Companion',
          platform: 'cross-platform',
          lastSyncedAt: '2026-03-24T09:31:11.000Z',
          syncState: 'healthy',
        },
      ],
      syncCoveragePercent: 99,
      syncTimeMs: 640,
      crossDeviceContinuity: true,
      pendingConflicts: 0,
      lastConflictResolvedAt: '2026-03-24T09:15:00.000Z',
    }
  },

  async getWalletAnalytics(): Promise<WalletAnalyticsSnapshot> {
    await delay(100)
    return analyticsSnapshot
  },
}
